from __future__ import annotations

from io import BytesIO
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


BLUE = "00338D"
CYAN = "00A3E0"
LIGHT_BLUE = "EAF3FF"
LIGHT_GRAY = "F3F6FA"
GREEN = "12805C"
ORANGE = "B45309"
RED = "C0262D"
WHITE = "FFFFFF"
BORDER = "D9E2EF"


def safe(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, (str, int, float, bool)):
        return value
    return str(value)


def status_text(status: str) -> str:
    return {"missing": "缺失", "warn": "待确认", "ok": "已匹配"}.get(status, status or "")


def setup_sheet(sheet, title: str) -> None:
    sheet.sheet_view.showGridLines = False
    sheet.freeze_panes = "A4"
    sheet["A1"] = title
    sheet["A1"].font = Font(bold=True, size=16, color=BLUE)
    sheet["A2"] = "Generated by AI-MESP Workpaper Copilot"
    sheet["A2"].font = Font(color="64748B", size=10)


def style_table(sheet, header_row: int, max_row: int, max_col: int) -> None:
    thin = Side(style="thin", color=BORDER)
    for cell in sheet[header_row]:
        if cell.column <= max_col:
            cell.fill = PatternFill("solid", fgColor=BLUE)
            cell.font = Font(bold=True, color=WHITE)
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            cell.border = Border(bottom=thin)

    for row in sheet.iter_rows(min_row=header_row + 1, max_row=max_row, max_col=max_col):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = Border(bottom=thin)


def autofit(sheet, min_width: int = 10, max_width: int = 48) -> None:
    widths = {}
    for row in sheet.iter_rows():
        for cell in row:
            if cell.value is None:
                continue
            text = str(cell.value)
            widths[cell.column] = max(widths.get(cell.column, min_width), min(max_width, len(text) + 2))
    for column, width in widths.items():
        sheet.column_dimensions[get_column_letter(column)].width = width


def write_rows(sheet, start_row: int, headers: list[str], rows: list[list[Any]]) -> int:
    for col, header in enumerate(headers, 1):
        sheet.cell(start_row, col, header)
    for r, row in enumerate(rows, start_row + 1):
        for c, value in enumerate(row, 1):
            sheet.cell(r, c, safe(value))
    max_row = start_row + len(rows)
    style_table(sheet, start_row, max_row, len(headers))
    return max_row


def build_summary_sheet(wb: Workbook, result: dict) -> None:
    ws = wb.active
    ws.title = "Summary"
    setup_sheet(ws, "MESP Workpaper Summary")
    summary = result.get("summary", {})

    cards = [
        ("Program", result.get("program") or "-"),
        ("Period", result.get("period") or "-"),
        ("Samples", summary.get("sample_count", 0)),
        ("Recognized Files", summary.get("recognized_file_count", 0)),
        ("Workbooks", summary.get("workbook_count", 0)),
        ("Missing Items", summary.get("missing_file_count", 0)),
        ("Warnings", summary.get("warning_count", 0)),
        ("Evidence Trace Items", len(result.get("evidence_trace") or [])),
    ]

    for index, (label, value) in enumerate(cards):
        row = 4 + index // 4 * 3
        col = 1 + index % 4 * 3
        ws.cell(row, col, label)
        ws.cell(row + 1, col, value)
        ws.merge_cells(start_row=row, start_column=col, end_row=row, end_column=col + 1)
        ws.merge_cells(start_row=row + 1, start_column=col, end_row=row + 1, end_column=col + 1)
        ws.cell(row, col).fill = PatternFill("solid", fgColor=LIGHT_BLUE)
        ws.cell(row, col).font = Font(bold=True, color=BLUE)
        ws.cell(row + 1, col).font = Font(bold=True, size=14)
        ws.cell(row, col).alignment = Alignment(horizontal="center")
        ws.cell(row + 1, col).alignment = Alignment(horizontal="center")

    counts = summary.get("workbook_count_by_report") or {}
    rows = [[report, counts.get(report, 0)] for report in ["CO03", "KSBT", "3611", "CKM3"]]
    write_rows(ws, 12, ["Report", "Workbook Count"], rows)
    autofit(ws)


def build_issues_sheet(wb: Workbook, result: dict) -> None:
    ws = wb.create_sheet("Exception Summary")
    setup_sheet(ws, "Exception Summary")
    rows = [
        [
            issue.get("type"),
            issue.get("sample"),
            issue.get("problem"),
            issue.get("suggestion"),
            status_text(issue.get("status", "")),
        ]
        for issue in result.get("issues", [])
    ]
    if not rows:
        rows = [["No exception noted.", "", "", "", "已匹配"]]
    write_rows(ws, 4, ["Type", "Sample", "Problem", "Suggestion", "Status"], rows)
    for row in range(5, 5 + len(rows)):
        status = ws.cell(row, 5).value
        color = GREEN if status == "已匹配" else RED if status == "缺失" else ORANGE
        ws.cell(row, 5).font = Font(bold=True, color=color)
    autofit(ws)


def build_mapping_sheet(wb: Workbook, result: dict) -> None:
    ws = wb.create_sheet("SAP Mapping")
    setup_sheet(ws, "SAP Field Mapping and Amount Summary")
    rows = []
    for item in result.get("workbook_results") or result.get("co03_results") or []:
        totals = item.get("totals") or {}
        rows.append(
            [
                item.get("sample"),
                item.get("report"),
                item.get("order") or "-",
                item.get("file"),
                item.get("sheet"),
                item.get("row_count"),
                item.get("column_count"),
                len(item.get("mapping") or {}),
                len(item.get("missing_fields") or []),
                "\n".join(f"{key}: {value}" for key, value in totals.items()),
            ]
        )
    write_rows(
        ws,
        4,
        [
            "Sample",
            "Report",
            "Order",
            "Source File",
            "Sheet",
            "Rows",
            "Columns",
            "Mapped Fields",
            "Missing Fields",
            "Totals",
        ],
        rows,
    )
    autofit(ws)


def build_trace_sheet(wb: Workbook, result: dict) -> None:
    ws = wb.create_sheet("Evidence Traceability")
    setup_sheet(ws, "Evidence Traceability")
    rows = [
        [
            item.get("sample"),
            item.get("order"),
            item.get("report"),
            item.get("workpaper_field"),
            item.get("source_file"),
            item.get("source_sheet"),
            item.get("source_header"),
            item.get("source_column"),
            item.get("status"),
        ]
        for item in result.get("evidence_trace", [])
    ]
    write_rows(
        ws,
        4,
        [
            "Sample",
            "Order",
            "Report",
            "Workpaper Field",
            "Source File",
            "Source Sheet",
            "Source Header",
            "Source Column",
            "Status",
        ],
        rows,
    )
    autofit(ws)


def build_checklist_sheet(wb: Workbook, result: dict) -> None:
    ws = wb.create_sheet("AI Review Checklist")
    setup_sheet(ws, "AI Review Checklist")
    rows = [
        [index + 1, question.get("title"), question.get("body"), question.get("ask"), "Open"]
        for index, question in enumerate(result.get("questions", []))
    ]
    if not rows:
        rows = [[1, "No open review question", "No exception noted.", "", "Closed"]]
    write_rows(ws, 4, ["No.", "Review Point", "Observation", "Suggested Follow-up", "Status"], rows)
    autofit(ws)


def build_recalculation_sheet(wb: Workbook, result: dict) -> None:
    ws = wb.create_sheet("Recalculation")
    setup_sheet(ws, "Recalculation Workpaper")
    rows = [
        ["Selected Program", result.get("program") or "-", ""],
        ["Audit Period", result.get("period") or "-", ""],
        ["Formula - Variance Allocation Rate", "(Beginning variance + Current-period variance) / (Beginning inventory + Current-period receipts)", "To be calculated after CKM3 line-category mapping"],
        ["Formula - Allocated Variance", "Variance allocation rate x Current-period issues", "To be calculated after CKM3 line-category mapping"],
    ]
    write_rows(ws, 4, ["Item", "Value / Formula", "Status"], rows)
    autofit(ws)


def build_workpaper_workbook(result: dict) -> Workbook:
    wb = Workbook()
    build_summary_sheet(wb, result)
    build_issues_sheet(wb, result)
    build_mapping_sheet(wb, result)
    build_trace_sheet(wb, result)
    build_checklist_sheet(wb, result)
    build_recalculation_sheet(wb, result)
    return wb


def build_workpaper_bytes(result: dict) -> bytes:
    wb = build_workpaper_workbook(result)
    stream = BytesIO()
    wb.save(stream)
    return stream.getvalue()
